### ISSUE TITLE
Enhancement: option to generate static type based on the runtype

### ISSUE THREAD

**Issue by haradzienski** [cobraz/generate-runtypes#28]
Hi there! ✋ 

First of all, thank you for such a wonderful library - I've played with version `2.0.0-alpha-3` a bit, and it's awesome!

I am using the lib to generate runtypes based on an OpenAPI v2 (Swagger) spec, and I think it would be nice if there was an option to generate a static type (`type Something = rt.Static<typeof something>;`) based on the root type. I think it could work similar to how `export` flag currently works. I checked out the code, and looks like it could be as easy as adding one more `conditionalWrite` to this function: https://github.com/cobraz/generate-runtypes/blob/develop/src/main.ts#L84-L89.

I could make a PR if that's something you'd be willing to pull in.

Looking forward to hearing from you, and thanks again!

**Comment by runeh** [comment]
Sounds totally reasonable to me to support this.

**Comment by runeh** [comment]
Should be a fairly small change. Might need to propagate some options to the various writers, but that should be straight-forward.

**Comment by runeh** [comment]
I tried this out. Almost no code, so that's good 👍  See PR.

One issue here, what to do about naming? have the runtype name be lowercase and the type name be uppercase? 

Should it be configurable?  We could support a callback for creating the names I suppose, for anyone that wants something else than the default.

Should the default be to create types or not?

Thoughts @haradzienski @cobraz  ?

**Comment by cobraz** [comment]
> I am using the lib to generate runtypes based on an OpenAPI v2 (Swagger) spec

@haradzienski I would love to help out with that! It has been a wish for quite some time to build a tool that can do just that. I've currently only written some documentation/planning: https://gist.github.com/cobraz/a0031905833bc58d233451fe537f3019

I'm pretty sure there are lots of people who wants that to help :)

**Comment by cobraz** [comment]
> One issue here, what to do about naming? have the runtype name be lowercase and the type name be uppercase?
I like the lower/upper-case version!

> Should it be configurable? We could support a callback for creating the names I suppose, for anyone that wants something else than the default.
Probably a good thing!

> Should the default be to create types or not?
We should probably create it by default!

**Comment by runeh** [comment]
Updated

**Comment by haradzienski** [comment]
> @haradzienski I would love to help out with that! It has been a wish for quite some time to build a tool that can do just that. I've currently only written some documentation/planning: https://gist.github.com/cobraz/a0031905833bc58d233451fe537f3019
> 
> I'm pretty sure there are lots of people who wants that to help :)

@cobraz unfortunately the code for it is not in a public repo right now. I'll see what I can do to open-source it though.

@runeh I've checked out the PR, looks great - thank you so much for implementing that! I left a small comment regarding an edge case in default behavior, but otherwise - can't wait to try it out.
